Repository erobotkh/erobot_mobile, pull requests merged in 2021-06, with the labels that each got.

#52 49 reputation detail screen
  assets/images/to-recieve.png
  lib/models/home_card_model.dart
  lib/screens/home/ir_remoter_screen.dart
  lib/screens/home/members_screen.dart
  lib/screens/home/reputation/local_widgets/image_viewer.dart
  lib/screens/home/reputation/reputation_detail_screen.dart
  lib/screens/home/reputation/reputations_screen.dart
  lib/widgets/er_back_button.dart
  lib/widgets/er_profile_image.dart
  pubspec.lock
  pubspec.yaml
Labels: Design

#56 55 fix conflict
  ios/Podfile.lock
  lib/app_router.dart
  lib/models/e_chip_model.dart
  lib/screens/accounts/local_widgets/e_dont_have_acc.dart
  lib/screens/accounts/local_widgets/e_forget_password.dart
  lib/screens/accounts/login_screen.dart
  lib/screens/education/education_screen.dart
  lib/screens/send_page/sender_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#59 57 sender screen update
  lib/app.dart
  lib/app_router.dart
  lib/config/tab_bar_config.dart
  lib/constant/app_constant.dart
  lib/constant/theme_constant.dart
  lib/models/home_card_model.dart
  lib/notifier/sender_screen_notifier.dart
  lib/screens/send_page/sender_screen.dart
  lib/screens/sender/sender_screen.dart
  lib/storage/base_list_storage.dart
  lib/storage/sender_recent_storage.dart
  lib/storage/share_preference_storage.dart
  lib/widgets/er_tap_effect.dart
Labels: Design, enhancement

#61 60 fix navigation
  lib/models/home_card_model.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/members_expaned_screen.dart
  lib/screens/home/members_screen.dart
  lib/screens/home/reputation/reputations_screen.dart
  lib/widgets/e_expansiontile.dart
  lib/widgets/er_expansion_tile.dart
Labels: enhancement
