Repository erobotkh/erobot_mobile, pull requests merged in 2021-11, with the labels that each got.

#82 close #81 bluetooth screen
  lib/models/bluetooth_device_model.dart
  lib/screens/home/bluetooth_screen/bluetooth_detail_screen.dart
  lib/screens/home/bluetooth_screen/bluetooth_screen.dart
  lib/screens/home/bluetooth_screen/local_widgets/er_alert_dailog.dart
  lib/screens/home/bluetooth_screen/local_widgets/er_listtile_widets.dart
  lib/screens/sender/sender_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation

#93 close #92 app bar main screen
  analysis_options.yaml
  lib/app/modules/wrapper/controllers/wrapper_controller.dart
  lib/app/modules/wrapper/views/wrapper_view.dart
  lib/config/tab_bar_config.dart
Labels: enhancement

#95 close #94 setup config & constant
  .gitignore
  lib/app.dart
  lib/app/modules/wrapper/controllers/wrapper_controller.dart
  lib/app/modules/wrapper/views/wrapper_view.dart
  lib/configs/app_config.dart
  lib/configs/tab_bar_config.dart
  lib/configs/theme_config.dart
  lib/constants/api_constant.dart.example
  lib/constants/config_constant.dart
  lib/constants/theme_constant.dart
Labels: migrate

#97 89 migrate network to getx
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  json_samples/links.json
  json_samples/meta.json
  json_samples/user_token.json
  lib/app/data/models/base_list_model.dart
  lib/app/data/models/links_model.dart
  lib/app/data/models/meta_model.dart
  lib/app/data/models/object_name_url_model.dart
  lib/app/data/models/user_token_model.dart
  lib/configs/config_environments.dart
  lib/helpers/app_helper.dart
  lib/main.dart
  lib/services/base_apis/auth_api.dart
  lib/services/base_apis/base_api.dart
  lib/services/base_apis/base_resource_api.dart
  lib/services/base_apis/networks/default_network.dart
  lib/services/base_apis/networks/user_token_network.dart
  lib/services/base_storages/base_preference_storage.dart
  lib/services/base_storages/bool_preference_storage.dart
  lib/services/base_storages/list_preference_storage.dart
  lib/services/base_storages/map_preference_storage.dart
  lib/services/storages/user_token_storage.dart
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#99 close #98 improve api after migrate
  android/.project
  android/.settings/org.eclipse.buildship.core.prefs
  android/app/.classpath
  android/app/.project
  android/app/.settings/org.eclipse.buildship.core.prefs
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  json_samples/post.json
  lib/app.dart
  lib/app/data/mixins/toast.dart
  lib/app/data/models/base/base_list_model.dart
  lib/app/data/models/base/links_model.dart
  lib/app/data/models/base/meta_model.dart
  lib/app/data/models/base/object_name_url_model.dart
  lib/app/data/models/post_list_model.dart
  lib/app/data/models/post_model.dart
  lib/app/data/widgets/er_email_field.dart
  lib/app/data/widgets/er_list_tile.dart
  lib/app/data/widgets/er_loading.dart
  lib/app/data/widgets/er_main_action_button.dart
  lib/app/data/widgets/er_password_field.dart
  lib/app/data/widgets/er_tap_effect.dart
  lib/app/data/widgets/er_text_field.dart
  lib/app/modules/account_detail/bindings/account_detail_binding.dart
  lib/app/modules/account_detail/views/account_detail_view.dart
  lib/app/modules/education/controllers/education_controller.dart
  lib/app/modules/education/local_widgets/education_card.dart
  lib/app/modules/education/views/education_view.dart
  lib/app/modules/login/bindings/login_binding.dart
  lib/app/modules/login/controllers/login_controller.dart
  lib/app/modules/login/local_widgets/auth_header.dart
  lib/app/modules/login/views/login_view.dart
  lib/app/modules/profile_detail/bindings/profile_detail_binding.dart
  lib/app/modules/profile_detail/controllers/profile_detail_controller.dart
  lib/app/modules/profile_detail/views/profile_detail_view.dart
  lib/app/modules/profile_wrapper/controllers/profile_wrapper_controller.dart
  lib/app/modules/profile_wrapper/views/profile_wrapper_view.dart
  lib/app/modules/register/controllers/register_controller.dart
  lib/app/modules/register/views/register_view.dart
  lib/app/modules/wrapper/bindings/wrapper_binding.dart
  lib/app/routes/app_pages.dart
  lib/app/routes/app_routes.dart
  lib/configs/theme_config.dart
  lib/constants/theme_constant.dart
  lib/services/apis/post_api.dart
  lib/services/base_apis/auth_api.dart
  lib/services/base_apis/base_api.dart
  lib/services/base_apis/base_app_api.dart
  lib/services/base_apis/base_resource_api.dart
  lib/services/base_apis/interceptors/default_interceptor.dart
  lib/services/base_apis/interceptors/user_token_inteceptor.dart
  lib/services/base_apis/networks/app_network.dart
  lib/services/base_apis/networks/base_network.dart
  lib/services/base_apis/networks/default_network.dart
  lib/services/base_apis/networks/user_token_network.dart
  lib/services/base_apis/retry_policy/refresh_token_policy.dart
  pubspec.lock
  pubspec.yaml
  test/app/data/models/object_name_url_model.dart
Labels: bug, enhancement

#102 close #101 setup json serializer
  build.yaml
  json_samples/links.json
  json_samples/meta.json
  json_samples/post.json
  json_samples/user_token.json
  lib/app/data/models/base/base_list_model.dart
  lib/app/data/models/base/links_model.dart
  lib/app/data/models/base/links_model.g.dart
  lib/app/data/models/base/meta_model.dart
  lib/app/data/models/base/meta_model.g.dart
  lib/app/data/models/base/object_name_url_model.dart
  lib/app/data/models/base/object_name_url_model.g.dart
  lib/app/data/models/image_model.dart
  lib/app/data/models/image_model.g.dart
  lib/app/data/models/post_list_model.dart
  lib/app/data/models/post_model.dart
  lib/app/data/models/post_model.g.dart
  lib/app/data/models/user_model.dart
  lib/app/data/models/user_model.g.dart
  lib/app/data/models/user_token_model.dart
  lib/app/data/models/user_token_model.g.dart
  lib/app/modules/education/controllers/education_controller.dart
  lib/app/modules/education/local_widgets/education_card.dart
  lib/app/modules/education/views/education_view.dart
  lib/services/apis/post_api.dart
  lib/services/base_apis/auth_api.dart
  lib/services/base_apis/base_api.dart
  lib/services/base_apis/interceptors/user_token_inteceptor.dart
  lib/services/base_apis/retry_policy/refresh_token_policy.dart
  lib/services/storages/user_token_storage.dart
  pubspec.lock
  pubspec.yaml
  test/app/data/models/object_name_url_model.dart
Labels: enhancement

#103 close #100 improve readme.md
  .fvm/flutter_sdk
  .fvm/fvm_config.json
  README.md
  lib/services/apis/post_api.dart
  lib/services/base_apis/base_resource_owner_api.dart
Labels: documentation

#105 close #104 arrange folder
  lib/app/data/models/post_list_model.dart
  lib/app/modules/education/controllers/education_controller.dart
  lib/app/modules/education/local_widgets/education_card.dart
  lib/app/modules/education/views/education_view.dart
  lib/app/modules/login/views/login_view.dart
  lib/app/modules/profile_detail/views/profile_detail_view.dart
  lib/app/modules/profile_wrapper/views/profile_wrapper_view.dart
  lib/app/modules/register/views/register_view.dart
  lib/app/routes/app_routes.dart
  lib/mixins/toast.dart
  lib/models/base/base_list_model.dart
  lib/models/base/links_model.dart
  lib/models/base/links_model.g.dart
  lib/models/base/meta_model.dart
  lib/models/base/meta_model.g.dart
  lib/models/base/object_name_url_model.dart
  lib/models/base/object_name_url_model.g.dart
  lib/models/image_model.dart
  lib/models/image_model.g.dart
  lib/models/post_list_model.dart
  lib/models/post_model.dart
  lib/models/post_model.g.dart
  lib/models/user_model.dart
  lib/models/user_model.g.dart
  lib/models/user_token_model.dart
  lib/models/user_token_model.g.dart
  lib/services/apis/post_api.dart
  lib/services/base_apis/auth_api.dart
  lib/services/base_apis/base_api.dart
  lib/services/base_apis/interceptors/user_token_inteceptor.dart
  lib/services/base_apis/retry_policy/refresh_token_policy.dart
  lib/services/storages/user_token_storage.dart
  lib/widgets/er_email_field.dart
  lib/widgets/er_list_tile.dart
  lib/widgets/er_loading.dart
  lib/widgets/er_main_action_button.dart
  lib/widgets/er_password_field.dart
  lib/widgets/er_tap_effect.dart
  lib/widgets/er_text_field.dart
  test/app/data/models/object_name_url_model.dart
Labels: migrate
