Repository erobotkh/erobot_mobile, pull requests merged in 2021-12, with the labels that each got.

#126 close #125 refactor update controller name
  ios/Podfile.lock
  lib/app/modules/ball_shooter/bindings/ball_shooter_binding.dart
  lib/app/modules/ball_shooter/controllers/ball_shooter_controller.dart
  lib/app/modules/home/views/home_view.dart
  lib/app/modules/joystick/bindings/joystick_binding.dart
  lib/app/modules/joystick/controllers/joystick_controller.dart
  lib/app/modules/joystick/views/joystick_view.dart
  lib/app/modules/joystick/widgets/circular_slider.dart
  lib/app/modules/joystick/widgets/custom_app_bar.dart
  lib/app/modules/joystick/widgets/pad_bottons.dart
  lib/app/modules/joystick/widgets/widgets.dart
  lib/app/modules/thumbstick/bindings/thumbstick_binding.dart
  lib/app/modules/thumbstick/controllers/thumbstick_controller.dart
  lib/app/modules/thumbstick/views/thumbstick_view.dart
  lib/app/routes/app_pages.dart
  lib/app/routes/app_routes.dart
  lib/configs/config_constant.dart
  lib/models/home_card_model.dart
  lib/widgets/er_expansion_tile.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: enhancement, feature

#129 close #128 prototype controller
  lib/app/modules/iot_connection_setting/controllers/iot_controller.dart
  lib/app/modules/joystick/views/joystick_view.dart
  lib/app/modules/joystick/widgets/pad_bottons.dart
  lib/app/modules/sender/views/sender_view.dart
  lib/app/modules/thumbstick/views/thumbstick_view.dart
  lib/mixins/toast.dart
  lib/widgets/circle_view.dart
  lib/widgets/er_joystick.dart
  lib/widgets/er_tap_effect.dart
Labels: feature

#131 close #130 fix tap effect not cancel on tap up
  lib/widgets/er_tap_effect.dart
Labels: bug

#132 close #87 migrate post detail
  lib/app.dart
  lib/app/modules/education/local_widgets/education_card.dart
  lib/app/modules/education/views/education_view.dart
  lib/app/modules/post_detail/controllers/post_detail_controller.dart
  lib/app/modules/post_detail/views/post_detail_view.dart
  lib/widgets/er_image_viewer.dart
  pubspec.lock
  pubspec.yaml
Labels: migrate
